# -*- coding: utf-8 -*-
"""Lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Epz6YalCZp2ve2r4gbe49aQHthxf3yOx
"""

# Importing necessary libraries for data processing and model building

import numpy as np              # For numerical operations and handling arrays
import pandas as pd             # For data manipulation and analysis

import tensorflow as tf         # Core TensorFlow library for deep learning
from tensorflow.keras.models import Sequential   # To build a sequential neural network model
from tensorflow.keras.layers import LSTM, Embedding, Dense
# LSTM: For sequence learning (e.g., text, time-series)
# Embedding: Converts words into dense vectors
# Dense: Fully connected layer for output

from tensorflow.keras.preprocessing.sequence import pad_sequences
# Used to ensure all input sequences have the same length

from sklearn.model_selection import train_test_split
# Splits dataset into training and testing sets

# File paths for the dataset (stored in Google Drive)
ratings_path = "/content/drive/MyDrive/Lstm_project /ratings.csv"
movies_path = "/content/drive/MyDrive/Lstm_project /movies.csv"

# Load ratings dataset into a pandas DataFrame
df = pd.read_csv(ratings_path)

# Load movies dataset with proper encoding to handle special characters
movies_df = pd.read_csv(movies_path, encoding='latin1')

# Confirmation message to ensure data is loaded successfully
print("✅ Data loaded successfully!")

# Mapping: movieId -> title and genres
movieId_to_title = dict(zip(movies_df['movieId'], movies_df['title']))
movieId_to_genres = dict(zip(movies_df['movieId'], movies_df['genres']))

# Sort data by user and timestamp
df = df.sort_values(by=['userId', 'timestamp'])

# Create sequences of movie interactions for each user
user_sequences = df.groupby('userId')['movieId'].apply(list)

# Convert movie IDs to a contiguous range
unique_movies = sorted(df['movieId'].unique())
movie_to_index = {movie: i + 1 for i, movie in enumerate(unique_movies)}
index_to_movie = {i + 1: movie for i, movie in enumerate(unique_movies)}

# Map index to movie title and genres
index_to_movie_title = {index: movieId_to_title.get(movie_id, "Unknown Title") for index, movie_id in index_to_movie.items()}
index_to_movie_genres = {index: movieId_to_genres.get(movie_id, "Unknown Genre") for index, movie_id in index_to_movie.items()}

# Map movieId in df to indexes
df['movieId'] = df['movieId'].map(movie_to_index)

# Prepare input-output sequences
sequence_length = 5
X, y = [], []

for user_movies in user_sequences:
    indexed_movies = [movie_to_index[m] for m in user_movies if m in movie_to_index]
    for i in range(len(indexed_movies) - sequence_length):
        X.append(indexed_movies[i:i + sequence_length])
        y.append(indexed_movies[i + sequence_length])

X = pad_sequences(X, maxlen=sequence_length, padding='pre')
y = np.array(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build model
vocab_size = len(movie_to_index) + 1
embedding_dim = 50

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim),
    LSTM(64),
    Dense(vocab_size, activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train model
history = model.fit(X_train, y_train, epochs=2, batch_size=8, validation_data=(X_test, y_test))

# Model summary
model.summary()

# Recommendation function
def recommend_next_movie(movie_sequence):
    movie_sequence_idx = [movie_to_index.get(m, 0) for m in movie_sequence]
    movie_sequence_idx = pad_sequences([movie_sequence_idx], maxlen=sequence_length, padding='pre')
    prediction = model.predict(movie_sequence_idx, verbose=0)
    predicted_index = np.argmax(prediction, axis=-1)[0]

    movie_id = index_to_movie.get(predicted_index, "Unknown ID")
    movie_title = index_to_movie_title.get(predicted_index, "Unknown Title")
    movie_genre = index_to_movie_genres.get(predicted_index, "Unknown Genre")

    return movie_id, movie_title, movie_genre

# Example usage
example_sequence = user_sequences.iloc[0][:sequence_length]
predicted_movie_id, predicted_movie_title, predicted_movie_genre = recommend_next_movie(example_sequence)

print("\n✅ Prediction Results:")
print("Predicted next movie ID:", predicted_movie_id)
print("Predicted next movie title:", predicted_movie_title)
print("Predicted next movie genre:", predicted_movie_genre)